# Generated by Django 5.2.5 on 2025-08-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('nome_setor', models.CharField(max_length=30)),
                ('prioridade', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], default=('Baixa', 'Baixa'), max_length=5)),
                ('data_cadastro', models.DateField()),
                ('status', models.CharField(choices=[('A fazer', 'A fazer'), ('Fazendo', 'Fazendo'), ('Pronto', 'Pronto')], default=('A fazer', 'A fazer'), max_length=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kanban_app.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
