# Generated by Django 5.2.5 on 2025-08-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban_app', '0002_alter_usuarios_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
